[package]
name = "dataverse-computa-derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "computa_derive"
proc-macro = true

[dependencies]
quote = "1.0.33"
syn = "1.0.72"
proc-macro2 = "1.0.74"