name: Generate Doc

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - main
  pull_request:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build cargo doc
    runs-on: ubuntu-latest
    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"

    permissions:
      pages: write
      id-token: write
  
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.2
        with:
          version: "v0.4.0"

      - uses: ibnesayeed/setup-ipfs@master
        with:
          ipfs_version: ^0.24
          run_daemon: true

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install tree make -y

      - name: Run cargo doc
        run: make doc

      - name: Fix permissions
        run: |
          chmod -c -R +rX "target/doc/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: target/doc

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2